<template>
  <Echarts v-if="option.series.length" :option="option" />
  <a-empty v-else class="echarts-empty" />
</template>

<script>
import { listEnvironmentMonthlyPowerSubmodule } from "@/services/envMonth.js";
import dayJs from "dayjs";
import { tableConversion } from "./methods.js";
import Echarts from "@/components/echarts/index.vue";
import { barObj } from "@/pages/hiddenPerils/dataAnalysis/mixin/dataAnalysis.js";
import { isEmpty } from "lodash";
const markLineValue = 401.1;
export default {
  components: { Echarts },
  props: {
    dateStr: {},
  },
  data() {
    return {
      option: {
        tooltip: {
          ...barObj.tooltip,
        },
        grid: {
          top: "18%",
          left: "4px",
          right: "40px",
          bottom: "5%",
          containLabel: true,
        },
        legend: {},
        color: ["#5470c6", "#91cc75"],
        xAxis: [
          {
            type: "category",
            axisLabel: {
              ...barObj.xAxis.axisLabel,
            },
            axisPointer: {
              ...barObj.xAxis.axisPointer,
            },
          },
        ],
        yAxis: [
          {
            type: "value",
            name: "百万kwh",
            alignTicks: true,
            axisLine: {
              show: true,
            },
          },
          {
            offset: 40,
            type: "value",
            name: "kwh/m²",
            nameTextStyle: {
              align: "left",
            },
            max: undefined,
            alignTicks: true,
            axisLine: {
              // show: true,
            },
            axisLabel: {
              formatter: (v) => {
                let yAxisBalue = v.toFixed(1);
                return yAxisBalue;
              },
            },
          },
        ],
        series: [],
      },
      seriesDefault: [
        {
          name: "电量(百万kwh)",
          type: "bar",
          stack: "Ad",
          emphasis: {
            focus: "series",
          },
          barMaxWidth: 50,
          data: [],
        },
        {
          name: "电耗(kwh/m²)",
          type: "line",
          yAxisIndex: 1,
          markLine: {
            symbol: ["circle", "arrow"], //箭头
            data: [
              {
                silent: false, //鼠标悬停事件  true没有，false有
                lineStyle: {
                  //警戒线的样式  ，虚实  颜色
                  type: "dashed",
                  color: "#91cc75",
                  //利用阴影进行延长
                  // shadowOffsetX: 50,	//！！！！！！！！！
                  // shadowColor: '#91cc75'
                },
                label: {
                  position: "end",
                  formatter: "{c}",
                  color: "inherit",
                  // padding: [0, 0, 0, 10]
                },
                yAxis: markLineValue,
              },
            ],
          },
          data: [],
        },
      ],
    };
  },
  computed: {
    corporationList() {
      return this.$store.state.setting.corporationList;
    },
  },
  created() {
    this.getSubmodule();
  },
  methods: {
    //现地电量（最新月份的数据）
    async getSubmodule() {
      const apiData = {
        dataType: "",
        dateStr: this.dateStr,
        dateType: "1",
      };
      this.option.xAxis[0].data = [];
      const data = await listEnvironmentMonthlyPowerSubmodule(apiData);
      // const data = {
      //   data: {
      //     1004: [
      //       {
      //         monthlyId: "1765242839054303233",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694542182612994",
      //         corporationIds: null,
      //         nicheItemsCode: "1004",
      //         nicheItemsCodeList: null,
      //         dataItem: 38499087.74,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: 38499087.74,
      //         scope2: null,
      //         scopeSum: 38.49908774,
      //       },
      //       {
      //         monthlyId: "1765270892220399617",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "9760779",
      //         corporationId: "1586695220145717250",
      //         corporationIds: null,
      //         nicheItemsCode: "1004",
      //         nicheItemsCodeList: null,
      //         dataItem: 65126423,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: 65126423,
      //         scope2: null,
      //         scopeSum: 65.126423,
      //       },
      //       {
      //         monthlyId: "1766032589977100289",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586691844456611842",
      //         corporationIds: null,
      //         nicheItemsCode: "1004",
      //         nicheItemsCodeList: null,
      //         dataItem: 29066785.3,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: 29066785.3,
      //         scope2: null,
      //         scopeSum: 29.0667853,
      //       },
      //       {
      //         monthlyId: "1767798452191272961",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "812980337",
      //         corporationId: "1586697258397106177",
      //         corporationIds: null,
      //         nicheItemsCode: "1004",
      //         nicheItemsCodeList: null,
      //         dataItem: 12199884,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: 12199884,
      //         scope2: null,
      //         scopeSum: 12.199884,
      //       },
      //       {
      //         monthlyId: "1767845339481100289",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "9760779",
      //         corporationId: "1586695280988291073",
      //         corporationIds: null,
      //         nicheItemsCode: "1004",
      //         nicheItemsCodeList: null,
      //         dataItem: 63605840,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: 63605840,
      //         scope2: null,
      //         scopeSum: 63.60584,
      //       },
      //       {
      //         monthlyId: "1768193108255264770",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694597253824513",
      //         corporationIds: null,
      //         nicheItemsCode: "1004",
      //         nicheItemsCodeList: null,
      //         dataItem: 59340228,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: 59340228,
      //         scope2: null,
      //         scopeSum: 59.340228,
      //       },
      //       {
      //         monthlyId: "1768436424075534337",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694483395248129",
      //         corporationIds: null,
      //         nicheItemsCode: "1004",
      //         nicheItemsCodeList: null,
      //         dataItem: 74615094.74,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: 74615094.74,
      //         scope2: null,
      //         scopeSum: 74.61509474,
      //       },
      //       {
      //         monthlyId: "1768460602090004482",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694155505532930",
      //         corporationIds: null,
      //         nicheItemsCode: "1004",
      //         nicheItemsCodeList: null,
      //         dataItem: 51389434.42,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: 51389434.42,
      //         scope2: null,
      //         scopeSum: 51.38943442,
      //       },
      //       {
      //         monthlyId: "1769530330355146753",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694278159564801",
      //         corporationIds: null,
      //         nicheItemsCode: "1004",
      //         nicheItemsCodeList: null,
      //         dataItem: 62697646,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: 62697646,
      //         scope2: null,
      //         scopeSum: 62.697646,
      //       },
      //       {
      //         monthlyId: "1769883403543949314",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694083829071873",
      //         corporationIds: null,
      //         nicheItemsCode: "1004",
      //         nicheItemsCodeList: null,
      //         dataItem: 48095884,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: 48095884,
      //         scope2: null,
      //         scopeSum: 48.095884,
      //       },
      //     ],
      //     1110: [
      //       {
      //         monthlyId: "1765242839054303233",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694542182612994",
      //         corporationIds: null,
      //         nicheItemsCode: "1110",
      //         nicheItemsCodeList: null,
      //         dataItem: 228.57,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: null,
      //         scope2: null,
      //         scopeSum: null,
      //       },
      //       {
      //         monthlyId: "1765270892220399617",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "9760779",
      //         corporationId: "1586695220145717250",
      //         corporationIds: null,
      //         nicheItemsCode: "1110",
      //         nicheItemsCodeList: null,
      //         dataItem: 848.57,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: null,
      //         scope2: null,
      //         scopeSum: null,
      //       },
      //       {
      //         monthlyId: "1766032589977100289",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586691844456611842",
      //         corporationIds: null,
      //         nicheItemsCode: "1110",
      //         nicheItemsCodeList: null,
      //         dataItem: 139.19,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: null,
      //         scope2: null,
      //         scopeSum: null,
      //       },
      //       {
      //         monthlyId: "1767798452191272961",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "812980337",
      //         corporationId: "1586697258397106177",
      //         corporationIds: null,
      //         nicheItemsCode: "1110",
      //         nicheItemsCodeList: null,
      //         dataItem: 184.95,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: null,
      //         scope2: null,
      //         scopeSum: null,
      //       },
      //       {
      //         monthlyId: "1767845339481100289",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "9760779",
      //         corporationId: "1586695280988291073",
      //         corporationIds: null,
      //         nicheItemsCode: "1110",
      //         nicheItemsCodeList: null,
      //         dataItem: 949.54,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: null,
      //         scope2: null,
      //         scopeSum: null,
      //       },
      //       {
      //         monthlyId: "1768193108255264770",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694597253824513",
      //         corporationIds: null,
      //         nicheItemsCode: "1110",
      //         nicheItemsCodeList: null,
      //         dataItem: 103.45,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: null,
      //         scope2: null,
      //         scopeSum: null,
      //       },
      //       {
      //         monthlyId: "1768436424075534337",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694483395248129",
      //         corporationIds: null,
      //         nicheItemsCode: "1110",
      //         nicheItemsCodeList: null,
      //         dataItem: 93.3,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: null,
      //         scope2: null,
      //         scopeSum: null,
      //       },
      //       {
      //         monthlyId: "1768460602090004482",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694155505532930",
      //         corporationIds: null,
      //         nicheItemsCode: "1110",
      //         nicheItemsCodeList: null,
      //         dataItem: 145.27,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: null,
      //         scope2: null,
      //         scopeSum: null,
      //       },
      //       {
      //         monthlyId: "1769530330355146753",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694278159564801",
      //         corporationIds: null,
      //         nicheItemsCode: "1110",
      //         nicheItemsCodeList: null,
      //         dataItem: 107.49,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: null,
      //         scope2: null,
      //         scopeSum: null,
      //       },
      //       {
      //         monthlyId: "1769883403543949314",
      //         monthlyDate: "2024-02",
      //         corporationName: null,
      //         companyId: "1425357055446880256",
      //         centerId: "688553997",
      //         corporationId: "1586694083829071873",
      //         corporationIds: null,
      //         nicheItemsCode: "1110",
      //         nicheItemsCodeList: null,
      //         dataItem: 102.85,
      //         upPeriodDataItem: null,
      //         upYearDataItem: null,
      //         userId: null,
      //         dateType: null,
      //         dateStr: null,
      //         dataType: null,
      //         startMonth: null,
      //         endMonth: null,
      //         monthl: null,
      //         year: null,
      //         environmentMonthlyUp: null,
      //         environmentMonthlyUpYear: null,
      //         ringRatio: null,
      //         withThan: null,
      //         scope1: null,
      //         scope2: null,
      //         scopeSum: null,
      //       },
      //     ],
      //   },
      // };
      if (isEmpty(data.data)) {
        return;
      }
      this.$set(this.option, "series", this.seriesDefault);
      let obj = tableConversion(data.data, 1004);

      const titleList = obj.titleList;
      const tableData = obj.tableData;
      const xAxisData = [];
      const list = [];
      const array = [];
      for (let i of titleList) {
        const arr = this.corporationList.find((item) => item.corporationId == i);
        xAxisData.push(arr.orgAbbrName);
        for (let item of tableData) {
          const code = item.nicheItemsCode;
          if (code == 1004) {
            // this.option.series[0].data = [item[i]];
            list.push(item[i]);
          } else if (code == 1110) {
            // this.option.series[1].data = [item[i]];
            array.push(item[i]);
          }
        }
      }
      this.option.series[0].data = list;
      this.option.series[1].data = array;
      // y轴最大值
      let alarm = (this.option.series[1].data || [])
        .filter((item) => item)
        .map((item) => item - 0);
      let maxMarkLineArr = [...alarm].sort((x, y) => y - x);
      let maxMarkLineValue = maxMarkLineArr.length ? maxMarkLineArr[0] : 0;
      let yAxisMax =
        markLineValue <= maxMarkLineValue ? maxMarkLineValue : markLineValue + 10;
      this.option.yAxis[1].max = yAxisMax;

      // x轴
      this.option.xAxis[0].data = xAxisData;
      // console.log(this.option, "this.optionthis.optionthis.option");
    },
  },
};
</script>

<style lang="less" scoped>
.shenglvhao {
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
.title {
  font-size: 16px;
  font-weight: bold;
  color: 16px;
  line-height: 80px;
}
</style>
